### PR TITLE
WIP: Dockerized standalone

### PR DESCRIPTION
**Pull request by izaleu**
A very basic Docker example. Requires Docker and Docker Compose.

It builds four services:

api - the Express API server
client - the ReactJS app
ooth - the Ooth standalone server
mongodb - mongodb server

Note: the settings.js files in /client and /ooth must have the `monogUrl` set to the MongoDB service name instead of `localhost` when the project is run by Docker Compose. By default it should be `'mongodb://mongodb:27017/ooth'`

### To Run

1. `cd` into the standalone directory
2. copy the contents of `settings.dist.js` to `settings.js` and modify to suit your needs
3. copy the contents of`strategies.dist.js` to `strategies.js` and modify to suit your needs
3. `docker-compose build && docker-compose up`
4. open http://localhost:3000/ in your browser

### Next steps:

I'm not sure how much additional config for the Dockerized `ooth` service would be useful to have here, since I'm pretty new to the library.

### CODE REVIEW

**Comment by nmaro** [comment]
Hey thank you for the pull request! I'm going to test it at home, but going to skim over the code and provide some feedback.

**Comment by spacedarcy** [comment]
Update: I copied the ooth service's config to an external folder to simulate the base image eventually becoming a "black box." The config folder inside the image should only be used for local dev. There's probably a cleaner way to do this with volumes but it's pretty late here and I wanted to mention it before I nod off.

**Comment by katsanva** [comment]
Any updates on this, guys?

**Comment by izaleu** [comment]
TBH I feel like I wanna change this somehow (remove API/client maybe?) but without feedback I'm not sure what to do next.

**Comment by nmaro** [comment]
Sorry, wasn't aware that you need more feedback. I'll give it a closer look.

**Comment by katsanva** [comment]
@izaleu I'll propose you to update to latest master which has configuration changes
Since that changes you can pass mongodb configuration like

```yml
 ooth:
    build: ./ooth
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ooth
```

without mounting config dir.
If you prefer to mount config dir anyway, it will be really good to
- add configs dir to `.dockerignore`
- (optional) provide [NODE_CONFIG_DIR](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir) env variable
- mount config dir as `- ./config:/opt/config:ro` to make it read only

**Comment by nmaro** [comment]
I created my own `docker-compose.yml` files, check out the readme of [standalone](https://github.com/nmaro/ooth/tree/master/examples/standalone) and [integrated](https://github.com/nmaro/ooth/tree/master/examples/integrated) examples.

**Pull request closed without merging**
